### ISSUE TITLE
change up blockservice + exchange here

### ISSUE THREAD

**Issue by jbenet** [ipfs-inactive/go-blocks#1]
see https://github.com/ipfs/go-ipfs/issues/1429

**Comment by jbenet** [comment]
the blockservice is this extra unnecessary abstraction. it could very well just conform to Blockstore and simplify things. 
- [ ] blockservice -> blockstore
- [ ] move to either `go-ipfs/exchange/blockstore` (keeping exchange interface) or `go-blocks/networked` (removing exchange interface)

**Comment by whyrusleeping** [comment]
:+1: youre saying we should still have the Blockstore and Blockservice as part of the IpfsNode, right? (but with Blockservice being of type `Blockstore` instead of `Blockservice`)

I'm curious how the `AllKeysChan` method would work on a blockservice. would it just defer that call to its underlying blockstore?

**Comment by jbenet** [comment]
> (but with Blockservice being of type Blockstore instead of Blockservice)

Right. 

> I'm curious how the AllKeysChan method would work on a blockservice. would it just defer that call to its underlying blockstore?

Yeah. and could return an `errors.New("not supported")` for networked one
